# Generated by Django 3.2.7 on 2021-09-18 10:30

from django.db import migrations, models
import form_tf_idf.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_tf_idf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(unique=True, upload_to='documents/', validators=[form_tf_idf.models.validate_file_extension], verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки файла'),
        ),
    ]
